### ISSUE TITLE
ImportError: 'module' object has no attribute 'check_specifier'

### ISSUE THREAD

**Issue by xisafe** [p1r06u3/opencanary_web#11]
![image](https://user-images.githubusercontent.com/29724312/50873617-a8ba2000-13fb-11e9-8a5b-e622091fd67c.png)

**Comment by xisafe** [comment]
pip install --upgrade setuptools==30.1.0

解决

**Comment by p1r06u3** [comment]
@xisafe 老哥的动手能力好强

**Comment by xisafe** [comment]
An error has occurred: 'Couldn't listen on 172.16.16.74:3306: [Errno 98] Address already in use.

@p1r06u3 

原先机器有数据库，端口冲突agent就起不来，感觉可以做个配置，端口被占用就略过，这样就可以在有业务的机器上安装agent了，更真实。

**Comment by xisafe** [comment]
![image](https://user-images.githubusercontent.com/29724312/50874354-b45b1600-13fe-11e9-8c00-1b0d6217f38e.png)


老哥们真厉害，搭建好了，效果很赞 @p1r06u3

**Comment by p1r06u3** [comment]
@xisafe 业务机器上部署要小心一点，害怕不期望的错误对业务有影响~
