### ISSUE TITLE
Job for supervisord.service failed because the control process exited with error code. See "systemctl status supervisord.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by AngieQ1** [p1r06u3/opencanary_web#12]
[1] 13457
● supervisord.service - Process Monitoring and Control Daemon
   Loaded: loaded (/usr/lib/systemd/system/supervisord.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-01-09 11:16:34 CST; 5min ago
  Process: 13100 ExecStart=/usr/bin/supervisord -c /etc/supervisord.conf (code=exited, status=2)

Jan 09 11:16:34 localhost.localdomain systemd[1]: Starting Process Monitoring and Control Daemon...
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: Error: File contains no section headers.
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: file: /etc/supervisord.d/tornado.ini,... 1
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: 'do-8000,tornado-8001,tornado-8002,to...n'
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: For help, use /usr/bin/supervisord -h
Jan 09 11:16:34 localhost.localdomain systemd[1]: supervisord.service: control process exited, ...=2
Jan 09 11:16:34 localhost.localdomain systemd[1]: Failed to start Process Monitoring and Contro...n.
Jan 09 11:16:34 localhost.localdomain systemd[1]: Unit supervisord.service entered failed state.
Jan 09 11:16:34 localhost.localdomain systemd[1]: supervisord.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
-- 
-- The start-up result is done.
Jan 09 11:01:01 localhost.localdomain CROND[12143]: (root) CMD (run-parts /etc/cron.hourly)
Jan 09 11:01:01 localhost.localdomain run-parts(/etc/cron.hourly)[12146]: starting 0anacron
Jan 09 11:01:01 localhost.localdomain run-parts(/etc/cron.hourly)[12152]: finished 0anacron
Jan 09 11:16:34 localhost.localdomain polkitd[5431]: Registered Authentication Agent for unix-proces
Jan 09 11:16:34 localhost.localdomain systemd[1]: Starting Process Monitoring and Control Daemon...
-- Subject: Unit supervisord.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit supervisord.service has begun starting up.
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: Error: File contains no section headers.
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: file: /etc/supervisord.d/tornado.ini, line
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: 'do-8000,tornado-8001,tornado-8002,tornado
Jan 09 11:16:34 localhost.localdomain supervisord[13100]: For help, use /usr/bin/supervisord -h
Jan 09 11:16:34 localhost.localdomain systemd[1]: supervisord.service: control process exited, code=
Jan 09 11:16:34 localhost.localdomain systemd[1]: Failed to start Process Monitoring and Control Dae
-- Subject: Unit supervisord.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit supervisord.service has failed.
-- 
-- The result is failed.
Jan 09 11:16:34 localhost.localdomain systemd[1]: Unit supervisord.service entered failed state.
Jan 09 11:16:34 localhost.localdomain systemd[1]: supervisord.service failed.
Jan 09 11:16:34 localhost.localdomain polkitd[5431]: Unregistered Authentication Agent for unix-proc

请问一下supervisord.service启动失败如何解决？

**Comment by p1r06u3** [comment]
@AngieQ1 可以参考下这个文章，看看是否有帮助：https://www.cnblogs.com/gefeng/p/8657264.html
可能是编码问题？麻烦解决以后，到这边来贴一下答案。

**Comment by AngieQ1** [comment]
> @AngieQ1 可以参考下这个文章，看看是否有帮助：https://www.cnblogs.com/gefeng/p/8657264.html
> 可能是编码问题？麻烦解决以后，到这边来贴一下答案。

把/etc/supervisord.conf和etc/supervisord.d/tornado.ini都设置成ascii 还是不行呢

**Comment by p1r06u3** [comment]
下班了我teamviewer帮你看下吧~wechat:pirogue-tk

**Comment by AngieQ1** [comment]
因为自己粗心输错了tornado.ini 这个文件！！！然后还麻烦大佬给我远程了！！真的很蠢！！希望各位认真输入文件！！！谢谢细心又nice的大佬！！！
