### ISSUE TITLE
你好 安装AGENT端时 21端口出现以下情况需要如何解决

### ISSUE THREAD

**Issue by ghost** [p1r06u3/opencanary_web#14]
![image](https://user-images.githubusercontent.com/24852223/50950785-0034ba80-14e6-11e9-9da4-9e56150911a5.png)

**Comment by p1r06u3** [comment]
@Mr89898 端口被占用了，您需要修改配置：/root/.opencanary.conf 关于ftp协议和21端口的开关或更改。
