### ISSUE TITLE
客户端问题

### ISSUE THREAD

**Issue by onlyaiai** [p1r06u3/opencanary_web#15]
安装完客户端显示安装成功，但是服务端看不到客户端

**Comment by p1r06u3** [comment]
@onlyaiai 
首先看下客户端进程是不是起来了 ，是不是存在opencanary进程
```
ps aux|grep python
```
如果起来了，看下客户端配置的serverip地址对不对，因为客户端是每10秒钟向web请求post请求一次，如果地址不对，肯定post不上去，日志/var/tmp/opencanary.log。

如果没起来就运行opencanaryd --start 看日志/var/tmp/opencanary.log，端口是不是占用了

**Comment by p1r06u3** [comment]
问题解决，原因是opencanary需要root权限启动。
