### ISSUE TITLE
Failed to start Supervisor daemon

### ISSUE THREAD

**Issue by shellb0y** [p1r06u3/opencanary_web#21]
supervisord.service: control process exited, code=exited status=203
Failed to start Supervisor daemon.
Unit supervisord.service entered failed state.
supervisord.service failed.

**Comment by p1r06u3** [comment]
这是supervisor的报错，supervisor是单独的一个组件，可以检查一下它的配置文件是否有错误，也可以看下具体的错误日志。

**Comment by p1r06u3** [comment]
@shellb0y 你也可以加我微信: pirogue-tk
我拉你到opencanary的微信答疑群里
