### ISSUE TITLE
502错误

### ISSUE THREAD

**Issue by wangwensx** [p1r06u3/opencanary_web#25]
自动安装完后出现，访问服务器端，出现502错误

**Comment by p1r06u3** [comment]
烦请提供错误日志。建议排错方向：nginx是否启动，tornado是否启动，tornado的mysql数据库密码是否连接正确。
可以加我微信:pirogue-tk 无偿提供技术支持

**Comment by IceRainow** [comment]
我也出现了这种情况

**Comment by p1r06u3** [comment]
@wangwensx https://github.com/p1r06u3/opencanary_web/issues/26
