### ISSUE TITLE
添加白名单ip提交没有报错，但是实际上没有保存新的ip信息

### ISSUE THREAD

**Issue by chenqy1** [p1r06u3/opencanary_web#30]
web添加白名单ip后提交配置不生效，刷新或下次登录查看白名单ip依然是旧的信息

**Comment by p1r06u3** [comment]
白名单ip需要手工进入数据库插入，白名单端口可以从后台点击按钮添加。😆

**Comment by p1r06u3** [comment]
@chenqy1 请修改一下报警邮箱，我这边收到了很多告警邮件，可能是您在测试时候发送的。
