### ISSUE TITLE
多个agent 怎么显示不出来

### ISSUE THREAD

**Issue by 420944022** [p1r06u3/opencanary_web#31]
多个agent 怎么显示不出来，总只看到一个。。

**Comment by 420944022** [comment]
显示出来了。但是一个更改了名称的。。原来那个需要删除..

**Comment by p1r06u3** [comment]
@420944022 删除的话需要登录数据库删除，界面上没有开发删除按钮😬

**Comment by 420944022** [comment]
删除了，后来自动会显示出来。又错误删除，上来比较快！

**Comment by p1r06u3** [comment]
/root/.opencanary.conf 这里面是agent的节点名称和客户端ip地址的修改，修改完成之后，重启下。旧的就不会再上线了，你现在改的这个新的就会上线了。

**Comment by 420944022** [comment]
我直接进入到库中，通过下面命令删除掉'online‘


delete from Host where status='online';



就会马上自动上线！   非常感谢您的回复!    
但是我发现一个问题，就是新建立的agent   不会马上在后台显示出来。。 我也通过上面命令，也好像就马上跑出来了。



------------------ 原始邮件 ------------------
发件人: "pirogue"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:08
收件人: "p1r06u3/opencanary_web"<opencanary_web@noreply.github.com>;
抄送: "海军"<420944022@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [p1r06u3/opencanary_web] 多个agent 怎么显示不出来 (#31)




/root/.opencanary.conf 这里面是agent的节点名称和客户端ip地址的修改，修改完成之后，重启下。旧的就不会再上线了，你现在改的这个新的就会上线了。

**Comment by p1r06u3** [comment]
@420944022 哈哈~ 那就等一等呗~ 
https://github.com/p1r06u3/opencanary/blob/master/opencanary/modules/host.py
可以看下这个客户端代码的第51行，这里设置了10秒钟会向服务器请求一次。

**Comment by 420944022** [comment]
恩，非常感谢！

我目前用在了服务器区域，每个网段部署了一个agent，还是可以发现里面服务器里面的问题的。特别是如果一个服务器中毒，就会去尝试连接同网段的其他服务器，这样就可以发现问题。非常实用！ 觉得只要搞个好点的UI。 再优化下。。可以变成一个产品。。

我原来打算一个服务器agnet，因为是云环境，配置多个网卡，发现那样不行，可能同网段可以发现问题，但是可能连接到后台还是会只有一个agent 。 





------------------ 原始邮件 ------------------
发件人: "pirogue"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:16
收件人: "p1r06u3/opencanary_web"<opencanary_web@noreply.github.com>;
抄送: "海军"<420944022@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [p1r06u3/opencanary_web] 多个agent 怎么显示不出来 (#31)




@420944022 哈哈~ 那就等一等呗~
 https://github.com/p1r06u3/opencanary/blob/master/opencanary/modules/host.py
 可以看下这个客户端代码的第51行，这里设置了10秒钟会向服务器请求一次。

**Comment by p1r06u3** [comment]
@420944022 谢谢 兄弟肯定~ 我也有打算，有时间了用golang重写一个版本，商业化一次试试。

**Comment by 420944022** [comment]
个人感觉，后台不管怎么样，前台只要够炫酷，就可以卖得出去，特别是政府单位.. 但是对于真实使用的人，还是觉得要实用。

建议：

大部分功能还是需要放置到前台。。   

报警，像爆破类，应该要多次（设置个阈值）才告警。  不然报警真的特多。我都不敢开放外网的。 








------------------ 原始邮件 ------------------
发件人: "pirogue"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午4:25
收件人: "p1r06u3/opencanary_web"<opencanary_web@noreply.github.com>;
抄送: "海军"<420944022@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [p1r06u3/opencanary_web] 多个agent 怎么显示不出来 (#31)




@420944022 谢谢 兄弟肯定~ 我也有打算，有时间了用golang重写一个版本，商业化一次试试。

**Comment by 420944022** [comment]
从后台看到的攻击时间，是以哪个为准。。是agent发过来的 还是以我后台收到的时间为准

**Comment by p1r06u3** [comment]
实际上都是一样的，只要你的系统时间正确。另外，这是一个内网低交互蜜罐。不适合放置于公网。

**Comment by 420944022** [comment]
你好。。 安装客户端时出现这个，怎么解决。。
Using legacy setup.py install for opencanary, since package 'wheel' is not installed.
Using legacy setup.py install for pyinotify, since package 'wheel' is not installed.
Installing collected packages: pyinotify, opencanary
&nbsp; Attempting uninstall: pyinotify
&nbsp; &nbsp; Found existing installation: pyinotify 0.9.4
ERROR: Cannot uninstall 'pyinotify'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by p1r06u3** [comment]
请加我微信:pirogue-tk

420944022 <notifications@github.com> 于2020年6月12日周五 上午12:38写道：

**Comment by p1r06u3** [comment]
github不常上，请加我微信:pirogue-tk
