### ISSUE TITLE
邮箱配置正常，但无法通过smtp发邮件

### ISSUE THREAD

**Issue by 30wish-xh** [p1r06u3/opencanary_web#33]
请问大佬一下后台smtp设置均已完成后仍无法正常发送邮件告警。是需要特定攻击触发，还是攻击列表中存在的攻击行为就会发送呢？

**Comment by p1r06u3** [comment]
攻击列表中存在就会发送邮件。检查一下opencanary_web/util/conf/email.ini

**Comment by 30wish-xh** [comment]
> 攻击列表中存在就会发送邮件。检查一下opencanary_web/util/conf/email.ini

看了一下switch也是on的状态，默认smtp连接端口25么？邮箱运营商ssl加密会有影响么？拜谢

**Comment by pench3r** [comment]
建议添加一个功能发送测试邮件。这样就不用等攻击触发再检测邮件功能是否正常了。

**Comment by p1r06u3** [comment]
@30wish-xh @pench3r 我发送邮件的功能只适配了163的smtp邮箱，其他自定义的可能需要测试。不好意思。

**Comment by pench3r** [comment]
嗯嗯 好的。

**Comment by 30wish-xh** [comment]
> @30wish-xh @pench3r 我发送邮件的功能只适配了163的smtp邮箱，其他自定义的可能需要测试。不好意思。
发现是个低级错误。。。自动化安装没安装全，重新安装就好了，其他邮箱我是sina的可以，其他理论上也可以，多谢大佬
