### ISSUE TITLE
建议加一个攻击列表过滤功能，放外网之后一下就几万页看不完的，谢谢。

### ISSUE THREAD

**Issue by UCHAMDRA** [p1r06u3/opencanary_web#34]
建议加一个攻击列表过滤功能，放外网之后一下就几万页看不完的。

**Comment by p1r06u3** [comment]
这个蜜罐原本定位是内网的交互蜜罐~方外网的效果会不好。因为放在内网相当于“埋地雷”，只要有人碰到它就产生告警了，而企业内部的定时正常请求来源，加白名单就可以了。这样就可以达到只要产生的syn网络链接就是攻击。

**Comment by kay6666** [comment]
> 建议加一个攻击列表过滤功能，放外网之后一下就几万页看不完的。

放在外网可以实现邮件炸弹-。-

**Comment by p1r06u3** [comment]
公网蜜罐推荐这个：https://github.com/hacklcx/HFish
