### ISSUE TITLE
ip登录不上怀疑nginx出现问题

### ISSUE THREAD

**Issue by kay6666** [p1r06u3/opencanary_web#35]
![100](https://user-images.githubusercontent.com/50900788/60769751-3c984a80-a106-11e9-9567-714601065736.png)
![101](https://user-images.githubusercontent.com/50900788/60769752-3d30e100-a106-11e9-9114-516eec1749f9.png)
![102](https://user-images.githubusercontent.com/50900788/60769753-3d30e100-a106-11e9-85a1-2ac7e45a3bb2.png)
![103](https://user-images.githubusercontent.com/50900788/60769754-3d30e100-a106-11e9-98f5-9b5b353d4947.png)

之前配置过域名登录  之后就？域名撤了就拉了库里了？登录不上去后台  不想重新安装想解决问题！

**Comment by p1r06u3** [comment]
私聊我 宝贝
