### ISSUE TITLE
如何将客户端探针部署在自己已有的web服务上？

### ISSUE THREAD

**Issue by RenJunFeng** [p1r06u3/opencanary_web#37]
自己有一个web服务，比如phpmyadmin，如何在phpmyadmin上部署探针，可以让web端可以监控到有谁对 phpmyadmin进行攻击呢？

**Comment by p1r06u3** [comment]
这个不可以哦~而且这是一个内网低交互蜜罐，不建议放到公网，作用不明显。
你这相当于流量监控的需求，不是蜜罐啊。
不过这个想法是一个好想法，后面开发商业版的话或许会考虑进去。

**Comment by p1r06u3** [comment]
推荐这个蜜罐：https://github.com/hacklcx/HFish
