### ISSUE TITLE
打不开蜜罐登录页

### ISSUE THREAD

**Issue by AhrendsSchmidt** [p1r06u3/opencanary_web#47]
按照教程把服务安装好，服务并且都正常启动，访问设置好的IP地址显示nginx主页，但是nginx的目录已经指向了蜜罐系统的static目录，访问还是nginx的欢迎页，配置过程中没有出现问题，请问这是怎么回事呢？

**Comment by p1r06u3** [comment]
请查看nginx和tornado日志

**Comment by AhrendsSchmidt** [comment]
问题已经解决了，谢谢。可以打开登陆页面了，但是无法登陆，报错位置是某个js出错了

**Comment by p1r06u3** [comment]
加我微信吧：pirogue-tk

**Comment by p1r06u3** [comment]
问题原因：
1.  mysql数据库链接密码自己修改过，没有修改蜜罐后台的数据库配置文件；
2. mysql数据库报“ performance_schema.session_status' doesn't exist”错误，可能是自己修改过数据库相关表或者是配置。

解决方法：
1. 将蜜罐后台的数据库配置文件修改与正在使用的数据库相对应；
2. https://blog.csdn.net/liulangshusheng2012/article/details/80347919
