### ISSUE TITLE
手动测试没有生成攻击日志

### ISSUE THREAD

**Issue by medasz** [p1r06u3/opencanary_web#60]
我把客户端和服务端安装到一台虚拟机，同时服务端开启80端口做监听，修改了配置文件中的http协议的端口，手动访问21和http协议端口没有生成对应的攻击日志

**Comment by p1r06u3** [comment]
按理说不应该呀，加我微信：pirogue-tk。
人工远程在线答疑～

**Comment by medasz** [comment]
蜜罐的ssh服务远程连接报错已解决
