### ISSUE TITLE
有点代码洁癖

### ISSUE THREAD

**Issue by EBWi11** [p1r06u3/opencanary_web#8]
为什么要将.DS_Store和.pyc一起上传...个人认为应该add .gitignore...

**Comment by p1r06u3** [comment]
Coding我是菜鸟~
学习了，这就改一下。
大佬也可以帮忙改改代码结构，分层啥的~

> 为什么要将.DS_Store和.pyc一起上传...个人认为应该add .gitignore...

**Comment by LiuJerome** [comment]
好像项目交流群满了 怎么进入

**Comment by p1r06u3** [comment]
@LiuJerome 加我微信吧: pirogue-tk
我拉您进去~

**Comment by z0edff0x3d** [comment]
@p1r06u3 楼上大哥我也想进群，带带弟弟
